<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_LoadcellScaling" Id="{976f5398-c837-4944-8db6-b5f1f3ab8dcc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_LoadcellScaling
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL.uLoadCellScaledValue := F_Scale(GVL.uLoadCellRawValue, 0.0, 1.0, -383, 1200);]]></ST>
    </Implementation>
    <LineIds Name="PRG_LoadcellScaling">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>