<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_Thermocouple" Id="{e6cc8783-084e-4bc3-b764-ac1c0275a869}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Thermocouple
VAR
	fTemp: REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fTemp := GVL.nTemp;]]></ST>
    </Implementation>
    <LineIds Name="PRG_Thermocouple">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>